### ISSUE TITLE
Some of the notebooks are broken

### ISSUE THREAD

**Issue by juliangilbey** [has2k1/plotnine-examples#16]
Hi!
I just tried running `make all` on this collection of notebooks, and ran into several errors:

Error 1: `geom_map.ipynb`.  The issue here is that the example repeatedly uses the `draw` keyword to `geom_map`, but it is not recognised.  Perhaps something changed in the options it accepts since this example was made?
```
[NbConvertApp] ERROR | Error while converting 'geom_map.ipynb'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# colors
water_color = '#a3ccff'
wall_color = 'white'
road_color = 'brown'

# Create label text by merging the territory name and
# the claimant to the territory
def fmt_labels(names, claimants):
    labels = []
    for name, claimant in zip(names, claimants):
        if name:
            labels.append('{} ({})'.format(name, claimant))
        else:
            labels.append('({})'.format(claimant))
    return labels

# Gallery Plot

(ggplot()
 + geom_map(westeros, fill=None)
 + geom_map(islands, fill=None)
 + geom_map(political, aes(fill='ClaimedBy'), color=None, show_legend=False)
 + geom_map(wall, draw='LineString', color=wall_color, size=2)
 + geom_map(lakes, fill=water_color, color=None)
 + geom_map(rivers, aes(size='size'), draw='LineString', color=water_color, show_legend=False)
 + geom_map(roads, aes(size='size'), draw='LineString', color=road_color, alpha=0.5, show_legend=False)
 + geom_map(cities, draw='Point', size=1)
 + geom_text(
     political,
     aes('geometry.centroid.x', 'geometry.centroid.y', label='fmt_labels(name, ClaimedBy)'),
     size=8,
     fontweight='bold'
 )
 + geom_text(
     cities,
     aes('geometry.centroid.x', 'geometry.centroid.y', label='name'),
     size=8,
     ha='left',
     nudge_x=.20
 )
 + labs(title="The Political Territories of Westeros")
 + scale_fill_brewer(type='qual', palette=8)
 + scale_x_continuous(expand=(0, 0, 0, 1))
 + scale_y_continuous(expand=(0, 1, 0, 0))
 + scale_size_continuous(range=(0.4, 1))
 + theme_void()
 + theme(figure_size=(8, 12), panel_background=element_rect(fill=water_color))
)
------------------

---------------------------------------------------------------------------
PlotnineError                             Traceback (most recent call last)
<ipython-input-3-2504ab68aa83> in <module>
     21  + geom_map(islands, fill=None)
     22  + geom_map(political, aes(fill='ClaimedBy'), color=None, show_legend=False)
---> 23  + geom_map(wall, draw='LineString', color=wall_color, size=2)
     24  + geom_map(lakes, fill=water_color, color=None)
     25  + geom_map(rivers, aes(size='size'), draw='LineString', color=water_color, show_legend=False)

/usr/lib/python3/dist-packages/plotnine/geoms/geom_map.py in __init__(self, mapping, data, **kwargs)
     51                 "Please install geopandas."
     52             )
---> 53         geom.__init__(self, mapping, data, **kwargs)
     54         # Almost all geodataframes loaded from shapefiles
     55         # have a geometry column.

/usr/lib/python3/dist-packages/plotnine/geoms/geom.py in __init__(self, mapping, data, **kwargs)
     50         self._stat = stat.from_geom(self)
     51         self._position = position.from_geom(self)
---> 52         self._verify_arguments(kwargs)     # geom, stat, layer
     53 
     54     @staticmethod

/usr/lib/python3/dist-packages/plotnine/geoms/geom.py in _verify_arguments(self, kwargs)
    396             msg = ("Parameters {}, are not understood by "
    397                    "either the geom, stat or layer.")
--> 398             raise PlotnineError(msg.format(unknown))
    399 
    400     def handle_na(self, data):

PlotnineError: "Parameters {'draw'}, are not understood by either the geom, stat or layer."
PlotnineError: "Parameters {'draw'}, are not understood by either the geom, stat or layer."
```

Error 2: `geom_segment.ipynb`: this is complaining that it cannot order `point_data` because it is grouped on `country`. That's weird because `segment_data` is too.
```
[NbConvertApp] ERROR | Error while converting 'geom_segment.ipynb'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# Create a verb to order the countries. You can apply this verb to any
# dataframe with a country column
categories = list(segment_data['country'])[::-1]
ordered_country_dtype = pdtypes.CategoricalDtype(categories=categories, ordered=True)
order_country = define(country='country.astype(ordered_country_dtype)')

segment_data >>= order_country
point_data >>= order_country
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-68e44030031c> in <module>
      6 
      7 segment_data >>= order_country
----> 8 point_data >>= order_country

/usr/lib/python3/dist-packages/plydata/operators.py in __rrshift__(self, other)
    122         self.data = other
    123         func = get_verb_function(self.data, self.__class__.__name__)
--> 124         return func(self)
    125 
    126     def __call__(self, data):

/usr/lib/python3/dist-packages/plydata/dataframe/one_table.py in define(verb)
     52         return verb.data
     53 
---> 54     _check_modify_groups(verb)
     55     verb.env = verb.env.with_outer_namespace(_outer_namespace)
     56     with regular_index(verb.data):

/usr/lib/python3/dist-packages/plydata/dataframe/one_table.py in _check_modify_groups(verb)
     39     overwritten_groups = list(set(new_cols) & set(groups))
     40     if overwritten_groups:
---> 41         raise ValueError(
     42             "Columns {} cannot be modified because they are "
     43             "grouping variables.".format(overwritten_groups)

ValueError: Columns ['country'] cannot be modified because they are grouping variables.
ValueError: Columns ['country'] cannot be modified because they are grouping variables.
```

Error 3: timeout error with `miscellaneous-a-pyqt5-application.ipynb`. This is because this notebook waits for input. So it should probably be excluded from the Makefile's processing.
```
[NbConvertApp] Converting notebook miscellaneous-a-pyqt5-application.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] ERROR | Timeout waiting for execute reply (30s).
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 33, in <module>
    sys.exit(load_entry_point('nbconvert==5.6.1', 'console_scripts', 'jupyter-nbconvert')())
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/lib/python3/dist-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 571, in run_cell
    if self._passed_deadline(deadline):
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 541, in _passed_deadline
    self._handle_timeout()
  File "/usr/lib/python3/dist-packages/nbconvert/preprocessors/execute.py", line 504, in _handle_timeout
    raise TimeoutError("Cell execution timed out")
TimeoutError: Cell execution timed out
```

Best wishes,

Julian

**Comment by has2k1** [comment]
1. geom_map examples need some changes. Shapefiles used to be able include
geometries of different types and the `draw` parameter would select one
type over any others. If the shapefiles are correct the it should be enough
just to remove the `draw` parameter.

2. I recall fixing some edge cases in the previous/last plydata releases,
this may be a consequence. I'll check it out.

3. I think caught that one while preparing for the next release and which
was interrupted by a nationwide internet blackout.

**Comment by juliangilbey** [comment]
I'm sorry, it sounds like you've had a terrible time internet-wise recently.  Please don't think I'm trying to pester you with these bugs - I'm just recording them as I discover them; no urgency to fix them from my end.  I think what you've created is fantastic and I'm looking forward to using it!

I hope things get better for you soon!

**Comment by orsinium** [comment]
> 3. I think caught that one while preparing for the next release and which
> was interrupted by a nationwide internet blackout.

Oh, that sounds sad. I hope it's more stable now. Stay strong!

@juliangilbey thank you for the detailed report!

**Comment by has2k1** [comment]
Although frustrating they are small issues in the "grand scheme" of things.

**Comment by ovolve** [comment]
Not sure if related, but the changes from recent commit [fb6cc88](https://github.com/has2k1/plotnine-examples/commit/fb6cc8866564b034a106c0b71f34f84f815d36de) seem to be showing up on the "stable" version on readthedocs (currently 0.7.1, e.g. see https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_histogram.html#plotnine.geoms.geom_histogram). 

This breaks many of the examples:

> `<repr(<plotnine.ggplot.ggplot at 0x7fb96b90a710>) failed: plotnine.exceptions.PlotnineError: "Could not evaluate the 'y' mapping: 'after_stat(ncount)' (original error: name 'after_stat' is not defined)">`

**Comment by juliangilbey** [comment]
Thanks!
